version: "3.9"
services:
  mongodb:      
    build: ./mongodb
    image: mongodb
    container_name: mongodb  
    volumes:
      - ~/volumes/mongodata/mongobingo/data:/data/db
      - ~/volumes/mongodata/mongobingo/logs:/data/logs
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=2022
    command: mongod
    networks:
      mnet:
        aliases:
          - mongodb
          
  adminmaxx:
    image: adminmaxx     
    build: ./adminmaxx
    container_name: adminmaxx 
    links:
      - mongodb
    ports:
      - 2020:2020 
    depends_on:     
      - mongodb  
    networks:
     - mnet
  
networks:
  mnet:
    driver: bridge
